# Generated by Django 3.1.2 on 2020-12-11 09:42

from django.db import migrations, models
import utils.address
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('origin', utils.address.AddressField(default={})),
                ('current', utils.address.AddressField(default={})),
                ('destination', utils.address.AddressField(default={})),
                ('status', models.CharField(choices=[('Pr', 'Processed'), ('Pu', 'Picked Up'), ('Tr', 'In Transit'), ('Dl', 'Delivered'), ('Rt', 'Return Transit'), ('Rc', 'Returned To Seller'), ('Do', 'Out For Delivery')], default='Pr', max_length=2)),
            ],
        ),
    ]
