# Generated by Django 3.1.2 on 2020-11-10 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.address
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0002_apikey_business'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticServices',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.business')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', utils.address.AddressField(default={})),
                ('pan', models.CharField(max_length=13, unique=True)),
                ('gst', models.CharField(max_length=13, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('users.business',),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('origin', utils.address.AddressField(default={})),
                ('current', utils.address.AddressField(default={})),
                ('destination', utils.address.AddressField(default={})),
                ('status', models.CharField(choices=[('Pr', 'Processed'), ('Pu', 'Picked Up'), ('Tr', 'In Transit'), ('Dl', 'Delivered'), ('Rt', 'Return Transit'), ('Rc', 'Returned To Seller'), ('Do', 'Out For Delivery')], default='Pr', max_length=2)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.logisticservices')),
            ],
        ),
    ]
