# Generated by Django 3.1.2 on 2020-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20201211_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticservices',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
