# Generated by Django 3.1.2 on 2020-11-10 07:17

from django.db import migrations, models
import django.db.models.deletion
import utils.address


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_apikey_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('business_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.business')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', utils.address.AddressField(default={})),
                ('pan', models.CharField(max_length=13, unique=True)),
                ('gst', models.CharField(max_length=13, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            bases=('users.business',),
        ),
    ]
